---
- name: Change user password
  hosts:  all
  vars_files:
    - config.yml
  tasks:
  - name: Changing password
    become: true
    user:
      name: "{{ user.username }}"
      update_password: always
      password: "{{ user.password | password_hash('sha512') }}"
